---
- name: Install iptables-persistent
  apt:
    name: "iptables-persistent"
    state: latest

- name: copy iptables rules files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0700
  with_items:
    - src: "etc/iptables/rules.v4"
      dest: "/etc/iptables/rules.v4"
    - src: "etc/iptables/rules.v6"
      dest: "/etc/iptables/rules.v6"

- name: Apply v4 iptables rules
  shell: "{{ item }}"
  with_items:
    - iptables-restore -n /etc/iptables/rules.v4

- name: Apply v6 iptables rules
  shell: "{{ item }}"
  with_items:
    - ip6tables-restore -n /etc/iptables/rules.v6
  ignore_errors: yes
