---
- name: Install iptables-persistent
  apt:
    name: "iptables-persistent"
    state: present

- name: copy iptables v4 rules files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0700
  with_items:
    - src: "etc/iptables/rules.v4"
      dest: "/etc/iptables/rules.v4"
  notify:
    - Apply v4 iptables rules

- name: copy iptables v6 rules files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0700
  with_items:
    - src: "etc/iptables/rules.v6"
      dest: "/etc/iptables/rules.v6"
  notify:
    - Apply v6 iptables rules
