#!/bin/sh

iptables -t filter -F
iptables -t filter -X

iptables -t filter -P INPUT DROP
iptables -t filter -P OUTPUT DROP
iptables -t filter -P FORWARD DROP

iptables -t filter -A OUTPUT -o lo -s 0.0.0.0/0 -d 0.0.0.0/0 -j ACCEPT
iptables -t filter -A INPUT -i lo -s 0.0.0.0/0 -d 0.0.0.0/0 -j ACCEPT

iptables -A OUTPUT -o {{ ansible_default_ipv4['interface'] }} -s 0.0.0.0/0 -d 0.0.0.0/0 -p all -m state ! --state INVALID -j ACCEPT
iptables -A INPUT -i {{ ansible_default_ipv4['interface'] }} -s 0.0.0.0/0 -d 0.0.0.0/0 -p all -m state --state RELATED,ESTABLISHED -j ACCEPT

iptables -A INPUT -p tcp -i {{ ansible_default_ipv4['interface'] }} --dport {{ iptables_ssh_port }} -j ACCEPT
